Re-adds holopara injectors to uplink and ports "Majorly buffs standard holoparas"(with some changes)
HippieStation/HippieStation13 pull request #137
Opened 2017-02-10 20:44 UTC by gumner

lol

2017-02-10 20:48 UTC, GuyonBroadway commented
OH SHIT NIGGER YOU FORGOT TO FORBID IT FROM NUKE OPS!

Actually part of me wants to leave it in just to see how funny it gets.

2017-02-10 20:48 UTC, tortellinitony commented
dude it doesn't even compile

2017-02-10 20:52 UTC, gumner commented
code/game/objects/effects/spawners/lootdrop.dm:137:error: /obj/item/weapon/storage/daki: undefined type path
code/game/objects/structures/crates_lockers/closets/secure/security.dm:32:error: /obj/item/weapon/storage/daki: undefined type path
code/modules/uplink/uplink_item.dm:1240:error: : expected 1 arg

2017-02-10 20:52 UTC, gumner commented
great

2017-02-10 20:53 UTC, KittyKathy commented
I'll try to help you.

2017-02-10 20:55 UTC, gumner commented
thanks

2017-02-10 20:59 UTC, KittyKathy commented on code/modules/uplink/uplink_item.dm
> +		var/datum/uplink_item/I = [category][item]
Is there a reason for this change? It's causing the build to fail, you should change it back to `uplink_items[category][item]`.

2017-02-10 21:00 UTC, gumner commented on code/modules/uplink/uplink_item.dm
> +		var/datum/uplink_item/I = [category][item]
mhm porbally a missclick from me,thanks

2017-02-10 21:05 UTC, KittyKathy commented
Oh also you need to open tgstation.dme with dream maker and find the files
code\game\objects\items\weapons\storage\dakis.dm
code\modules\mob\living\carbon\monkey\emote.dm
code\modules\surgery\gender_reassignment.dm
and click the little checkbox next to them so they get included I think.

2017-02-10 21:15 UTC, yobob591 commented
jojo ops

2017-02-10 21:15 UTC, KittyKathy commented on code/modules/uplink/uplink_item.dm
> +
You can add this line `exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)` after the cost to make it traitor gamemode only.

2017-02-10 21:16 UTC, gumner commented on code/modules/uplink/uplink_item.dm
> +
yeah i tried and it said something like unknown var

2017-02-10 21:17 UTC, JohnGinnane commented
Changelog pls

2017-02-10 21:18 UTC, gumner commented
i thought the changelog was broken or something because we had /tg/ changelog

2017-02-10 21:19 UTC, gumner commented on code/modules/uplink/uplink_item.dm
> +
ok should work now

2017-02-10 21:22 UTC, KittyKathy commented
You do it in your first post so instead of lol it would be something like this.
🆑 Gummer
add: Is that a JoJo reference?
tweak: Did someone say JoJo ops? kill me now.
/🆑

2017-02-10 21:26 UTC, gumner commented
ehh i already did an .yml changelog

2017-02-10 21:27 UTC, KittyKathy commented on code/modules/uplink/uplink_item.dm
> +
That's weird did you copy paste it or write it out? Probably better to copy it from another line so line 2229 where the surplus crate excludes from other modes than traitor you can just copy that line and paste it at line 567.

2017-02-10 21:30 UTC, yobob591 commented
sugg

2017-02-10 21:32 UTC, KittyKathy commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
Umm you put it at the wrong place that's for the Syndicate Cyborg correct line wrong place put it at line 567.

2017-02-10 21:33 UTC, JohnGinnane commented
We're using a different way of doing changelogs. You do what Kitty said instead of making a changelog file, and a bot generates it

2017-02-10 21:33 UTC, gumner commented on code/modules/uplink/uplink_item.dm
> +	exclude_modes = list(/datum/game_mode/nuclear, /datum/game_mode/gang)
kek im a tard

2017-02-10 21:33 UTC, gumner commented
do i need to do it now that i did an .yml?

2017-02-10 21:34 UTC, JohnGinnane commented
Yes, remove the .yml

2017-02-10 21:37 UTC, KittyKathy commented
I don't think the yml changelogs work anymore just edit your first post and put this also delete the yml changelog file.

`:cl: Gumner`
`add: Ported standard holoparasite buffs`
`add: You can buy the holoparasite injector with traitor uplinks once again.`
`/:cl:`

2017-02-10 21:41 UTC, KittyKathy commented
Also don't forget to remove line 522 while makes the syndicate borg traitor only? meaning now nuke ops can't get it unless you fix that.

2017-02-10 21:46 UTC, gumner commented
should work now

2017-02-10 22:23 UTC, McBawbaggings commented
I'd rather just see holos back, I dunno how stronk the new /tg/ ones are?

2017-02-10 22:23 UTC, gumner commented
they dont exist,basically

2017-02-10 22:26 UTC, QuarianCommando commented
Guardian spirits do, I think. Saw something about them in the lavaland guide.

2017-02-10 22:27 UTC, gumner commented
yeah tarot cards do exist in lavaland loot

2017-02-10 22:30 UTC, McBawbaggings commented
By that I mean, bring back traitor kit and see how they fare before buffing them???

2017-02-10 22:31 UTC, gumner commented
its exactly the same as they were before rebase,and standard was weaker on rebase because before rebase his damage was 30,and now its 20

2017-02-10 23:27 UTC, McBawbaggings commented
No they weren't.
https://github.com/HippieStationCode/HippieStation13/blob/master/code/modules/mob/living/simple_animal/guardian/guardian.dm#L260
I'd also leave deflection out for now since I dunno how stronk the new holos are.

2017-02-10 23:38 UTC, yobob591 commented
they are just as strong as they were in the past dude

2017-02-10 23:46 UTC, gumner commented
new holo's are complete shit

2017-02-10 23:50 UTC, gumner commented
no holos were buffed(besides standard that im buffing rn)

2017-02-11 00:10 UTC, yobob591 commented
i completely forgot theres like 3 new holopara types that tg added

2017-02-11 21:54 UTC, JamieH commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +/mob/living/simple_animal/bullet_act(obj/item/projectile/P)
Shouldn't this call `..()` somewhere?

2017-02-11 23:40 UTC, gumner commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +/mob/living/simple_animal/bullet_act(obj/item/projectile/P)
should work now

2017-02-11 23:42 UTC, gumner commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +/mob/living/simple_animal/bullet_act(obj/item/projectile/P)
should work now

2017-02-13 23:53 UTC, Dudeinyourbackyard commented
go do it

2017-02-13 23:54 UTC, ghost requested changes

2017-02-13 23:54 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +	var/holopunchrng = null
no need to initialize this as null

2017-02-14 00:20 UTC, yobob591 commented
give me the jojoes

2017-02-14 21:47 UTC, gumner commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +	var/holopunchrng = null
should work now

2017-02-15 00:17 UTC, ghost requested changes

2017-02-15 00:17 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +				if(istype(target, /mob/living/carbon/human))
there is a macro for this

2017-02-15 00:17 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +				playsound(loc, src.attack_sound, 50, 1, 1)
no spam please

2017-02-15 00:17 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +				src.say("[src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry]\
no spam please

2017-02-15 00:19 UTC, gumner commented
it doesnt actually spam you normie,its just 3 characters being repeated

2017-02-15 00:21 UTC, WhiteFox08 commented
consider death

2017-02-15 00:33 UTC, gumner commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +				if(istype(target, /mob/living/carbon/human))
i dont get it

2017-02-15 00:34 UTC, gumner commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +				src.say("[src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry]\
how the fuck is that spam

2017-02-17 22:27 UTC, gumner commented
can someone fully review this

2017-02-17 22:47 UTC, ghost requested changes

2017-02-17 22:47 UTC, Chnkr commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	//bla bla bla reflect shit
This comment is bad

2017-02-17 22:47 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +	var/holopunchrng
This variable is never set

2017-02-17 22:47 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +	mob_reflect_chance = 40
40% chance on reflecting bullets? Seems a bit high

2017-02-17 22:47 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +				src.say("[src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry][src.battlecry]\
You are spamming the battlecry over and over for no reason, why?

2017-02-17 22:47 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +				if(istype(target, /mob/living/carbon/human))
There is a macro that checks if something is human, use it

2017-02-17 22:47 UTC, Chnkr commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +					src.say("[src.battlecry][src.battlecry][src.battlecry]")//i couldnt figure out how 2 do organ damage in this rebase so i just put other bad shit here.
Bad comment

2017-02-17 22:47 UTC, Chnkr commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		visible_message("<span class='danger'>The [P.name] gets reflected by [name]!</span>")
I'm pretty sure there is a cleaner way to do this, try looking at reflective armor

2017-02-17 23:18 UTC, gumner commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	//bla bla bla reflect shit
fuck off thats grudge

2017-02-17 23:19 UTC, gumner commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +	mob_reflect_chance = 40
only 10% more than ablative armor,and costs 20 tc

2017-02-18 01:20 UTC, gumner commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		visible_message("<span class='danger'>The [P.name] gets reflected by [name]!</span>")
what you mean cleaner?

2017-02-18 01:20 UTC, gumner commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +	var/holopunchrng
yeah i was told i dindt need to make it null some days ago

2017-02-18 01:21 UTC, gumner commented on code/modules/mob/living/simple_animal/guardian/types/standard.dm
> +					src.say("[src.battlecry][src.battlecry][src.battlecry]")//i couldnt figure out how 2 do organ damage in this rebase so i just put other bad shit here.
dude,just a comment b r a h

2017-02-20 16:28 UTC, JamieH commented
build this

2017-02-24 13:46 UTC, JohnGinnane commented
@gumner you still working on this?

2017-02-24 14:31 UTC, Chnkr commented
@JohnGinnane I think i scared him off with my review `:^)`

2017-02-25 01:26 UTC, gumner commented
yes i will go back to this,i was busy w/ school

2017-02-26 07:39 UTC, gumner commented
im closing this because i cant update my  branch for some reason

2017-02-26 07:39 UTC, closed without merging